services:
  postgres:
    image: postgres
    container_name: plataformaSquad1
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"

  api:
    build: 
      context: .
      dockerfile: dockerfile.api
    container_name: apiPlataformaDeInovacao
    env_file: .env
    ports:
      - 3000:3000
    depends_on:
      - postgres
    environment:
      DATABASE_URL: ${DATABASE_URL_CONTAINER}
    command: sh -c "npx prisma migrate deploy && npm run start:prod"